/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyERC20__factory } from "./MyERC20__factory";
export { StudentSocietyDAO__factory } from "./StudentSocietyDAO__factory";
